### ISSUE TITLE
you should probably add the .rhistory to .gitignore and remove the history file from github

### ISSUE THREAD

**Issue by RMHogervorst** [jhollist/rmd_word_manuscript#1]
Hi Jeffrey,

I see that you have committed the .rhistory and .rproject files to github. In the future you might want to add a .gitignore file like here <https://www.gitignore.io/api/r> that will ignore those files. 

I don't see any strange things in your history file, but you might never know if you typed in a password in the R console and unwittingly commit that to github. 

Kind regards,
Roel

**Comment by jhollist** [comment]
Thanks for the heads up, @RMHogervorst .  I do usually add those, but forgot this time.  I started the repo without intending to push to Github...  

Oops.
